/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.parser.antlr;

import com.google.inject.Inject;
import fr.inria.diverse.dmgen.parser.antlr.internal.InternalDMGenParser;
import fr.inria.diverse.dmgen.services.DMGenGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DMGenParser extends AbstractAntlrParser {

	@Inject
	private DMGenGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDMGenParser createParser(XtextTokenStream stream) {
		return new InternalDMGenParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GenConfig";
	}

	public DMGenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DMGenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
