/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DMGenAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/inria/diverse/dmgen/parser/antlr/internal/InternalDMGen.tokens");
	}
}
