/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.ui;

import com.google.inject.Injector;
import fr.inria.diverse.dmgen.ui.internal.DmgenActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DMGenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DmgenActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DmgenActivator.getInstance().getInjector(DmgenActivator.FR_INRIA_DIVERSE_DMGEN_DMGEN);
	}
	
}
