/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDMGenScopeProvider extends DelegatingScopeProvider {
}
