/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.ide.contentassist.antlr;

import com.google.inject.Inject;
import fr.inria.diverse.dmgen.ide.contentassist.antlr.internal.InternalDMGenParser;
import fr.inria.diverse.dmgen.services.DMGenGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class DMGenParser extends AbstractContentAssistParser {

	@Inject
	private DMGenGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDMGenParser createParser() {
		InternalDMGenParser result = new InternalDMGenParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGenConfigAccess().getDeployModeAlternatives_2_2_1_0(), "rule__GenConfig__DeployModeAlternatives_2_2_1_0");
					put(grammarAccess.getINTorUNBOUNDEDAccess().getAlternatives(), "rule__INTorUNBOUNDED__Alternatives");
					put(grammarAccess.getPACKAGEAccess().getAlternatives_1_0(), "rule__PACKAGE__Alternatives_1_0");
					put(grammarAccess.getFRAGMENTAccess().getAlternatives_1_0(), "rule__FRAGMENT__Alternatives_1_0");
					put(grammarAccess.getGenConfigAccess().getGroup(), "rule__GenConfig__Group__0");
					put(grammarAccess.getGenConfigAccess().getGroup_2_0(), "rule__GenConfig__Group_2_0__0");
					put(grammarAccess.getGenConfigAccess().getGroup_2_1(), "rule__GenConfig__Group_2_1__0");
					put(grammarAccess.getGenConfigAccess().getGroup_2_2(), "rule__GenConfig__Group_2_2__0");
					put(grammarAccess.getGenConfigAccess().getGroup_2_3(), "rule__GenConfig__Group_2_3__0");
					put(grammarAccess.getPACKAGEAccess().getGroup(), "rule__PACKAGE__Group__0");
					put(grammarAccess.getPACKAGEAccess().getGroup_1(), "rule__PACKAGE__Group_1__0");
					put(grammarAccess.getDECIMALAccess().getGroup(), "rule__DECIMAL__Group__0");
					put(grammarAccess.getGeneratorAccess().getGroup(), "rule__Generator__Group__0");
					put(grammarAccess.getGeneratorAccess().getGroup_3_0(), "rule__Generator__Group_3_0__0");
					put(grammarAccess.getGeneratorAccess().getGroup_3_1(), "rule__Generator__Group_3_1__0");
					put(grammarAccess.getGeneratorAccess().getGroup_5_0(), "rule__Generator__Group_5_0__0");
					put(grammarAccess.getGeneratorAccess().getGroup_5_1(), "rule__Generator__Group_5_1__0");
					put(grammarAccess.getGeneratorAccess().getGroup_7(), "rule__Generator__Group_7__0");
					put(grammarAccess.getMetamodelAccess().getGroup(), "rule__Metamodel__Group__0");
					put(grammarAccess.getClazzAccess().getGroup(), "rule__Clazz__Group__0");
					put(grammarAccess.getClazzAccess().getGroup_2(), "rule__Clazz__Group_2__0");
					put(grammarAccess.getClazzAccess().getGroup_3(), "rule__Clazz__Group_3__0");
					put(grammarAccess.getClazzAccess().getGroup_3_2(), "rule__Clazz__Group_3_2__0");
					put(grammarAccess.getRangeAccess().getGroup(), "rule__Range__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup_1_0(), "rule__Property__Group_1_0__0");
					put(grammarAccess.getPropertyAccess().getGroup_1_0_1(), "rule__Property__Group_1_0_1__0");
					put(grammarAccess.getPropertyAccess().getGroup_1_1(), "rule__Property__Group_1_1__0");
					put(grammarAccess.getURIAccess().getGroup(), "rule__URI__Group__0");
					put(grammarAccess.getURIAccess().getGroup_1(), "rule__URI__Group_1__0");
					put(grammarAccess.getURIAccess().getGroup_3(), "rule__URI__Group_3__0");
					put(grammarAccess.getFRAGMENTAccess().getGroup(), "rule__FRAGMENT__Group__0");
					put(grammarAccess.getFRAGMENTAccess().getGroup_1(), "rule__FRAGMENT__Group_1__0");
					put(grammarAccess.getFRAGMENTAccess().getGroup_2(), "rule__FRAGMENT__Group_2__0");
					put(grammarAccess.getGenConfigAccess().getMetamodelAssignment_1(), "rule__GenConfig__MetamodelAssignment_1");
					put(grammarAccess.getGenConfigAccess().getPackageAssignment_2_0_1(), "rule__GenConfig__PackageAssignment_2_0_1");
					put(grammarAccess.getGenConfigAccess().getHdfsMasterAssignment_2_1_1(), "rule__GenConfig__HdfsMasterAssignment_2_1_1");
					put(grammarAccess.getGenConfigAccess().getDeployModeAssignment_2_2_1(), "rule__GenConfig__DeployModeAssignment_2_2_1");
					put(grammarAccess.getGenConfigAccess().getNumberOfNodesAssignment_2_2_3(), "rule__GenConfig__NumberOfNodesAssignment_2_2_3");
					put(grammarAccess.getGenConfigAccess().getHbaseMasterAssignment_2_3_1(), "rule__GenConfig__HbaseMasterAssignment_2_3_1");
					put(grammarAccess.getGenConfigAccess().getGeneratorsAssignment_3(), "rule__GenConfig__GeneratorsAssignment_3");
					put(grammarAccess.getGenConfigAccess().getGeneratorsAssignment_4(), "rule__GenConfig__GeneratorsAssignment_4");
					put(grammarAccess.getGeneratorAccess().getNameAssignment_0(), "rule__Generator__NameAssignment_0");
					put(grammarAccess.getGeneratorAccess().getNumberAssignment_1(), "rule__Generator__NumberAssignment_1");
					put(grammarAccess.getGeneratorAccess().getSizeAssignment_3_0_1(), "rule__Generator__SizeAssignment_3_0_1");
					put(grammarAccess.getGeneratorAccess().getPrefixAssignment_3_1_1(), "rule__Generator__PrefixAssignment_3_1_1");
					put(grammarAccess.getGeneratorAccess().getGlobalDensityAssignment_5_0_1(), "rule__Generator__GlobalDensityAssignment_5_0_1");
					put(grammarAccess.getGeneratorAccess().getGlobalDeviationAssignment_5_1_1(), "rule__Generator__GlobalDeviationAssignment_5_1_1");
					put(grammarAccess.getGeneratorAccess().getClassesAssignment_6(), "rule__Generator__ClassesAssignment_6");
					put(grammarAccess.getGeneratorAccess().getClassesAssignment_7_1(), "rule__Generator__ClassesAssignment_7_1");
					put(grammarAccess.getMetamodelAccess().getNameAssignment_0(), "rule__Metamodel__NameAssignment_0");
					put(grammarAccess.getMetamodelAccess().getUriAssignment_1(), "rule__Metamodel__UriAssignment_1");
					put(grammarAccess.getClazzAccess().getNameAssignment_0(), "rule__Clazz__NameAssignment_0");
					put(grammarAccess.getClazzAccess().getRangeAssignment_1(), "rule__Clazz__RangeAssignment_1");
					put(grammarAccess.getClazzAccess().getDepthAssignment_2_1(), "rule__Clazz__DepthAssignment_2_1");
					put(grammarAccess.getClazzAccess().getPropertiesAssignment_3_1(), "rule__Clazz__PropertiesAssignment_3_1");
					put(grammarAccess.getClazzAccess().getPropertiesAssignment_3_2_1(), "rule__Clazz__PropertiesAssignment_3_2_1");
					put(grammarAccess.getRangeAccess().getLowerAssignment_1(), "rule__Range__LowerAssignment_1");
					put(grammarAccess.getRangeAccess().getUpperAssignment_3(), "rule__Range__UpperAssignment_3");
					put(grammarAccess.getPropertyAccess().getNameAssignment_0(), "rule__Property__NameAssignment_0");
					put(grammarAccess.getPropertyAccess().getRangeAssignment_1_0_0(), "rule__Property__RangeAssignment_1_0_0");
					put(grammarAccess.getPropertyAccess().getDensityAssignment_1_0_1_1(), "rule__Property__DensityAssignment_1_0_1_1");
					put(grammarAccess.getPropertyAccess().getVariationAssignment_1_1_1(), "rule__Property__VariationAssignment_1_1_1");
					put(grammarAccess.getURIAccess().getSchemeAssignment_0(), "rule__URI__SchemeAssignment_0");
					put(grammarAccess.getURIAccess().getAuthorityAssignment_1_0(), "rule__URI__AuthorityAssignment_1_0");
					put(grammarAccess.getURIAccess().getFragmentsAssignment_2(), "rule__URI__FragmentsAssignment_2");
					put(grammarAccess.getURIAccess().getFragmentsAssignment_3_1(), "rule__URI__FragmentsAssignment_3_1");
					put(grammarAccess.getGenConfigAccess().getUnorderedGroup_2(), "rule__GenConfig__UnorderedGroup_2");
					put(grammarAccess.getGeneratorAccess().getUnorderedGroup_3(), "rule__Generator__UnorderedGroup_3");
					put(grammarAccess.getGeneratorAccess().getUnorderedGroup_5(), "rule__Generator__UnorderedGroup_5");
					put(grammarAccess.getPropertyAccess().getUnorderedGroup_1(), "rule__Property__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalDMGenParser typedParser = (InternalDMGenParser) parser;
			typedParser.entryRuleGenConfig();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DMGenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DMGenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
