/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.dMGen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clazz</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.Clazz#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.Clazz#getRange <em>Range</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.Clazz#getDepth <em>Depth</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.Clazz#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getClazz()
 * @model
 * @generated
 */
public interface Clazz extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getClazz_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.Clazz#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Range</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(Range)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getClazz_Range()
   * @model containment="true"
   * @generated
   */
  Range getRange();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.Clazz#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(Range value);

  /**
   * Returns the value of the '<em><b>Depth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Depth</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depth</em>' attribute.
   * @see #setDepth(int)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getClazz_Depth()
   * @model
   * @generated
   */
  int getDepth();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.Clazz#getDepth <em>Depth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depth</em>' attribute.
   * @see #getDepth()
   * @generated
   */
  void setDepth(int value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.dmgen.dMGen.Property}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Properties</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getClazz_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

} // Clazz
