/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.dMGen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gen Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.GenConfig#getMetamodel <em>Metamodel</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.GenConfig#getGlobalDensity <em>Global Density</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.GenConfig#getGlobalVariation <em>Global Variation</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.GenConfig#getGenerators <em>Generators</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getGenConfig()
 * @model
 * @generated
 */
public interface GenConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Metamodel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Metamodel</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metamodel</em>' containment reference.
   * @see #setMetamodel(Metamodel)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getGenConfig_Metamodel()
   * @model containment="true"
   * @generated
   */
  Metamodel getMetamodel();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.GenConfig#getMetamodel <em>Metamodel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metamodel</em>' containment reference.
   * @see #getMetamodel()
   * @generated
   */
  void setMetamodel(Metamodel value);

  /**
   * Returns the value of the '<em><b>Global Density</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Density</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Density</em>' attribute.
   * @see #setGlobalDensity(int)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getGenConfig_GlobalDensity()
   * @model
   * @generated
   */
  int getGlobalDensity();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.GenConfig#getGlobalDensity <em>Global Density</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global Density</em>' attribute.
   * @see #getGlobalDensity()
   * @generated
   */
  void setGlobalDensity(int value);

  /**
   * Returns the value of the '<em><b>Global Variation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Variation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Variation</em>' attribute.
   * @see #setGlobalVariation(float)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getGenConfig_GlobalVariation()
   * @model
   * @generated
   */
  float getGlobalVariation();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.GenConfig#getGlobalVariation <em>Global Variation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global Variation</em>' attribute.
   * @see #getGlobalVariation()
   * @generated
   */
  void setGlobalVariation(float value);

  /**
   * Returns the value of the '<em><b>Generators</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.dmgen.dMGen.Generator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Generators</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generators</em>' containment reference list.
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getGenConfig_Generators()
   * @model containment="true"
   * @generated
   */
  EList<Generator> getGenerators();

} // GenConfig
