/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.dMGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.Property#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.Property#getDensity <em>Density</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.dMGen.Property#getVariation <em>Variation</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getProperty_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.Property#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Density</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Density</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Density</em>' attribute.
   * @see #setDensity(int)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getProperty_Density()
   * @model
   * @generated
   */
  int getDensity();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.Property#getDensity <em>Density</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Density</em>' attribute.
   * @see #getDensity()
   * @generated
   */
  void setDensity(int value);

  /**
   * Returns the value of the '<em><b>Variation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variation</em>' attribute.
   * @see #setVariation(int)
   * @see fr.inria.diverse.dmgen.dMGen.DMGenPackage#getProperty_Variation()
   * @model
   * @generated
   */
  int getVariation();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.dMGen.Property#getVariation <em>Variation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variation</em>' attribute.
   * @see #getVariation()
   * @generated
   */
  void setVariation(int value);

} // Property
