/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.impl;

import org.eclipse.emf.ecore.EClass;

import fr.inria.diverse.dmgen.DMGenPackage;
import fr.inria.diverse.dmgen.NumericalRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Numerical Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NumericalRuleImpl extends RuleImpl implements NumericalRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NumericalRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DMGenPackage.Literals.NUMERICAL_RULE;
  }

} //NumericalRuleImpl
