/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.dmgen.DMGenPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
