/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getNumber <em>Number</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getSize <em>Size</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getBasePath <em>Base Path</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getGlobalDensity <em>Global Density</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getGlobalDeviation <em>Global Deviation</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.Generator#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator()
 * @model
 * @generated
 */
public interface Generator extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.Generator#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.Generator#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.Generator#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

  /**
   * Returns the value of the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prefix</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' attribute.
   * @see #setPrefix(String)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_Prefix()
   * @model
   * @generated
   */
  String getPrefix();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.Generator#getPrefix <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' attribute.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(String value);

  /**
   * Returns the value of the '<em><b>Base Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Base Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Path</em>' attribute.
   * @see #setBasePath(String)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_BasePath()
   * @model
   * @generated
   */
  String getBasePath();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.Generator#getBasePath <em>Base Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Path</em>' attribute.
   * @see #getBasePath()
   * @generated
   */
  void setBasePath(String value);

  /**
   * Returns the value of the '<em><b>Global Density</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Density</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Density</em>' attribute.
   * @see #setGlobalDensity(int)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_GlobalDensity()
   * @model
   * @generated
   */
  int getGlobalDensity();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.Generator#getGlobalDensity <em>Global Density</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global Density</em>' attribute.
   * @see #getGlobalDensity()
   * @generated
   */
  void setGlobalDensity(int value);

  /**
   * Returns the value of the '<em><b>Global Deviation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Deviation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Deviation</em>' attribute.
   * @see #setGlobalDeviation(float)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_GlobalDeviation()
   * @model
   * @generated
   */
  float getGlobalDeviation();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.Generator#getGlobalDeviation <em>Global Deviation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global Deviation</em>' attribute.
   * @see #getGlobalDeviation()
   * @generated
   */
  void setGlobalDeviation(float value);

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.dmgen.Clazz}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see fr.inria.diverse.dmgen.DMGenPackage#getGenerator_Classes()
   * @model containment="true"
   * @generated
   */
  EList<Clazz> getClasses();

} // Generator
