/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numerical Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.dmgen.DMGenPackage#getNumericalRule()
 * @model
 * @generated
 */
public interface NumericalRule extends Rule
{
} // NumericalRule
