/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>URI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.dmgen.URI#getScheme <em>Scheme</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.URI#getAuthority <em>Authority</em>}</li>
 *   <li>{@link fr.inria.diverse.dmgen.URI#getFragments <em>Fragments</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.dmgen.DMGenPackage#getURI()
 * @model
 * @generated
 */
public interface URI extends EObject
{
  /**
   * Returns the value of the '<em><b>Scheme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scheme</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scheme</em>' attribute.
   * @see #setScheme(String)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getURI_Scheme()
   * @model
   * @generated
   */
  String getScheme();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.URI#getScheme <em>Scheme</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scheme</em>' attribute.
   * @see #getScheme()
   * @generated
   */
  void setScheme(String value);

  /**
   * Returns the value of the '<em><b>Authority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Authority</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authority</em>' attribute.
   * @see #setAuthority(String)
   * @see fr.inria.diverse.dmgen.DMGenPackage#getURI_Authority()
   * @model
   * @generated
   */
  String getAuthority();

  /**
   * Sets the value of the '{@link fr.inria.diverse.dmgen.URI#getAuthority <em>Authority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Authority</em>' attribute.
   * @see #getAuthority()
   * @generated
   */
  void setAuthority(String value);

  /**
   * Returns the value of the '<em><b>Fragments</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fragments</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fragments</em>' attribute list.
   * @see fr.inria.diverse.dmgen.DMGenPackage#getURI_Fragments()
   * @model unique="false"
   * @generated
   */
  EList<String> getFragments();

} // URI
