/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen;

import fr.inria.diverse.dmgen.AbstractDMGenRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DMGenRuntimeModule extends AbstractDMGenRuntimeModule {
}
