/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen;

import fr.inria.diverse.dmgen.DMGenStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DMGenStandaloneSetup extends DMGenStandaloneSetupGenerated {
  public static void doSetup() {
    DMGenStandaloneSetup _dMGenStandaloneSetup = new DMGenStandaloneSetup();
    _dMGenStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
