/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.ui.tests;

import com.google.inject.Injector;
import fr.inria.diverse.dmgen.ui.internal.DmgenActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DMGenUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DmgenActivator.getInstance().getInjector("fr.inria.diverse.dmgen.DMGen");
	}

}
