/**
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.dmgen.ui;

import fr.inria.diverse.dmgen.ui.AbstractDMGenUiModule;
import fr.inria.diverse.dmgen.ui.handlers.RunGenerationHandler;
import fr.inria.diverse.dmgen.ui.launch.DMGenLaunchConfiguration;
import org.eclipse.core.commands.AbstractHandler;
import org.eclipse.debug.core.model.LaunchConfigurationDelegate;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class DMGenUiModule extends AbstractDMGenUiModule {
  public DMGenUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
  
  public Class<? extends AbstractHandler> bindAbstractHandler() {
    return RunGenerationHandler.class;
  }
  
  public Class<? extends LaunchConfigurationDelegate> bindLaunchConfigurationDelagate() {
    return DMGenLaunchConfiguration.class;
  }
}
